---
- name: Core Config
  hosts: lyons103cores
  gather_facts: false
  connection: local

  tasks:

    - name: Create Vlans
      ios_config:
        provider: "{{ provider }}"
        lines: name {{ item.name }}
        parents: vlan {{ item.vlan_id }}
      with_items: "{{ vlans }}"
      tags: createvlans

    - name: Create Vlan Interfaces
      ios_config:
        provider: "{{ provider }}"
        lines:
          - ip address {{ item.ip }} {{ item.mask }}
          - no shutdown
        parents: interface {{ item.name }}
      with_items: "{{ svi_int }}"
      tags: createsvi

    - name: Set Root Bridge
      ios_config:
        provider: "{{ provider}}"
        lines: spanning-tree vlan {{ item.id }} root {{ item.role }}
      with_items: "{{ root_bri }}"
      tags: stp

    - name: Configure Trunk Ports
      ios_config:
        provider: "{{ provider }}"
        lines:
          - switchport trunk encapsulation dot1q
          - switchport mode trunk
          - switchport trunk native vlan 99
        parents: interface {{ item.port }}
      with_items: "{{ trunk_ports }}"
      tags: trunk_ports

    - name: Configure WAN Access
      ios_config:
        provider: "{{ provider }}"
        lines:
          - no switchport
          - ip add {{ wan_ip }} {{ wan_mask }}
        parents: interface {{ wan_port }}
      tags: wan_ports

    - name: Configure OSPF
      ios_config:
        provider: "{{ provider }}"
        lines:
          - network {{ ospf.network1 }} {{ ospf.wildcard1 }} area {{ ospf.area }}
          - network {{ ospf.network2 }} {{ ospf.wildcard2 }} area {{ ospf.area }}
        parents: "router ospf 1"
      tags: ospf

    - name: Configure Hostname
      ios_config:
        provider: "{{ provider }}"
        lines:
          - hostname {{ hostname }}
      tags: hostname