---
svi_int:
  - name: Vlan10
    ip: "{{ vlan10.ip }}"
    mask: "{{ vlan10.mask }}"

  - name: Vlan20
    ip: "{{ vlan20.ip }}"
    mask: "{{ vlan20.mask }}"

  - name: Vlan30
    ip: "{{ vlan30.ip }}"
    mask: "{{ vlan30.mask }}"

  - name: Vlan32
    ip: "{{ vlan32.ip }}"
    mask: "{{ vlan32.mask }}"

  - name: Vlan35
    ip: "{{ vlan35.ip }}"
    mask: "{{ vlan35.mask }}"

  - name: Vlan99
    ip: "{{ vlan99.ip }}"
    mask: "{{ vlan99.mask }}"

root_bri:
  - id: 10
    role: "{{ vlan10.root }}"
  - id: 20
    role: "{{ vlan20.root }}"
  - id: 30
    role: "{{ vlan30.root }}"
  - id: 32
    role: "{{ vlan32.root }}"
  - id: 35
    role: "{{ vlan35.root }}"
  - id: 99
    role: "{{ vlan99.root }}"

vlan10:
  ip: "10.{{ sitecode }}.10.1"
  mask: 255.255.255.0
  root: primary
  description: Data

vlan20:
  ip: "10.{{ sitecode }}.20.1"
  mask: 255.255.255.0
  root: primary
  description: Voice

vlan30:
  ip: "10.{{ sitecode }}.30.1"
  mask: 255.255.255.0
  root: primary
  description: Staff-WIFI

vlan32:
  ip: "10.{{ sitecode }}.32.1"
  mask: 255.255.255.0
  root: primary
  description: Student-WIFI

vlan35:
  ip: "10.{{ sitecode }}.35.1"
  mask: 255.255.255.0
  root: primary
  description: Guest-WIFI

vlan99:
  ip: "10.{{ sitecode }}.99.1"
  mask: 255.255.255.0
  root: primary
  description: Management

ospf:
  network1: "10.{{ sitecode }}.0.0"
  wildcard1: 0.0.255.255
  network2: "{{ wan_ip }}"
  wildcard2: 0.0.0.0
  area: 0

